### ISSUE TITLE
Cluster click problem on Chrome

### ISSUE THREAD

**Issue by devendraparte** [Esri/cluster-layer-js#38] opened 2017-01-25 10:58 UTC
Hello,
I have been having single and cluster click issues in Chrome. This has been happending on both yoru demo and my local copy. Basically the click event does not fire and the extent change event fires,

It is VERY hard to duplicate and othe only way to get the click back is to close all instacnes of the beowser. Clearning the cache, hard refresh does not work. Its very strange.

Is this a known issue?

Thanks,

**Comment by devendraparte** [comment] 2017-03-29 07:34
Any update on this

**Comment by ghost** [comment] 2017-08-02 13:46
Has anyone figured out a fix for this issue?

**Comment by jgravois** [comment] 2017-08-02 17:50
duplicate of #31

**Closed as completed by jgravois** 2017-08-02 17:50 UTC
